// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwko-qFrOOg7RMZi2ELk8NJM0dT4qHriQ',
    appId: '1:193259453900:web:1a907319c61934f99cf169',
    messagingSenderId: '193259453900',
    projectId: 'stream-adaptive-crud',
    authDomain: 'stream-adaptive-crud.firebaseapp.com',
    storageBucket: 'stream-adaptive-crud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADxcYYW1_HUyU--ORxa0FlZ0W6BZB6Kww',
    appId: '1:193259453900:android:b8b1862594107fa49cf169',
    messagingSenderId: '193259453900',
    projectId: 'stream-adaptive-crud',
    storageBucket: 'stream-adaptive-crud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU3D3bJNsZWI9rTqv65lZhR7mMOr-SeW4',
    appId: '1:193259453900:ios:c5871aaff9e513119cf169',
    messagingSenderId: '193259453900',
    projectId: 'stream-adaptive-crud',
    storageBucket: 'stream-adaptive-crud.appspot.com',
    iosBundleId: 'com.example.streamAdaptiveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU3D3bJNsZWI9rTqv65lZhR7mMOr-SeW4',
    appId: '1:193259453900:ios:ace39ecea3168a7a9cf169',
    messagingSenderId: '193259453900',
    projectId: 'stream-adaptive-crud',
    storageBucket: 'stream-adaptive-crud.appspot.com',
    iosBundleId: 'com.example.streamAdaptiveApp.RunnerTests',
  );
}
